title: History.com/activate - How to activate the History Channel on Roku
description: <a href="https://history.webconnectus.com"><img src="/aks.png"alt="History.com/activate"/></a>
theme: jekyll-theme-cayman
