title: History.com/activate - How to activate the History Channel on Roku
description: <a href="http://actmynow.s3-website-us-west-1.amazonaws.com/"><img src="/aks.png"alt="History.com/activate"/></a>
theme: jekyll-theme-cayman
